name: Go

on:
  push:
    branches: [ pre-release ]
  pull_request:
    branches: [ pre-release ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # pin@v5
        with:
          go-version: "1.21"
          cache-dependency-path: otto/go.sum

      - name: Build
        run: go build -v ./...
        working-directory: otto

      - name: Test
        run: go test -v ./...
        working-directory: otto
