name: Go

on:
  push:
    branches: [ pre-release ]
  pull_request:
    branches: [ pre-release ]

permissions:
  actions: read
  contents: read

jobs:
  build_go:
    name: "Build & Test (Go)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #pin v4.2.2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a #pin v5.2.0
        with:
          go-version: "stable"
          cache-dependency-path: otto/go.sum

      - name: Build
        run: go build -v ./...
        working-directory: otto

      - name: Test
        run: |
          cd otto
          go test -v ./...
          cd cmd/test
          go build
          ./test

  build_node:
    name: "Build & Test (Node)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #pin v4.2.2
        with:
          persist-credentials: false

      - name: Prepare
        id: cache_key
        run: |
          cd frontend
          echo "NPM_KEY=NPM_$(shasum package-lock.json | cut -d ' ' -f1)" >> "$GITHUB_OUTPUT"

      - name: Restore NPM Packages
        id: restore_npm
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf #pin v4.2.2
        with:
          key: ${{ steps.cache_key.outputs.NPM_KEY }}
          path: |
            frontend/node_modules

      - name: NPM Install
        id: npm_install
        if: ${{ steps.restore_npm.outputs.cache-hit != 'true' }}
        run: |
          cd frontend
          npm --prefer-offline ci

      - name: Webpack Build
        id: webpack_build
        run: |
          cd frontend
          node start_webpack.js
