name: Go

on:
  push:
    branches: [ pre-release ]
  pull_request:
    branches: [ pre-release ]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #pin v4.1.1

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 #pin v5.0.0
        with:
          go-version: "1.22"
          cache-dependency-path: otto/go.sum

      - name: Build
        run: go build -v ./...
        working-directory: otto

      - name: Test
        run: go test -v ./...
        working-directory: otto

      - name: Initialize CodeQL
        uses: github/codeql-action/init@3ab4101902695724f9365a384f86c1074d94e18c #pin v3.24.7
        with:
          languages: go

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@3ab4101902695724f9365a384f86c1074d94e18c #pin v3.24.7
        with:
          category: "/language:go"
