name: Go

on:
  push:
    branches: [pre-release]
  pull_request:
    branches: [pre-release]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # pin@v3.5.0

      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # pin@v4.0.0
        with:
          go-version: "1.20"

      - name: Build
        run: go build -v ./...
        working-directory: otto

      - name: Test
        run: go test -v ./...
        working-directory: otto

      - name: Initialize CodeQL
        uses: github/codeql-action/init@d186a2a36cc67bfa1b860e6170d37fb9634742c7 # pin@v2.2.11
        with:
          languages: go

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@d186a2a36cc67bfa1b860e6170d37fb9634742c7 # pin@2.2.11
        with:
          category: "/language:go"
