name: Go

on:
  push:
    branches: [pre-release]
  pull_request:
    branches: [pre-release]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # pin@v3.5.0

      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # pin@v3.5.0
        with:
          go-version: "1.20"

      - name: Build
        run: go build -v ./...
        working-directory: otto

      - name: Test
        run: go test -v ./...
        working-directory: otto

      - name: Initialize CodeQL
        uses: github/codeql-action/init@16964e90ba004cdf0cd845b866b5df21038b7723 # pin@v2.2.6
        with:
          languages: go

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@16964e90ba004cdf0cd845b866b5df21038b7723 # pin@2.2.6
        with:
          category: "/language:go"
